# -*- org-confirm-babel-evaluate: nil; -*-
#+TITLE: OYC Physics
#+OPTIONS: num:nil
#+STARTUP: indent
#+PROPERTY: header-args:axiom :results output :exports results
#+PROPERTY: header-args:latex :results drawer :exports results
#+INFOJS_OPT: view:overview toc:nil

* Initialization

#+BEGIN_SRC axiom :results silent
)set output characters default
#+END_SRC

* Problem Set III

** 1.

#+BEGIN_SRC axiom
  )clear all
  )read "input/III.1.input"
#+END_SRC

** 2.

The problem does not state whether $\mu$ or $\mu'$ are the
coefficients of static or kinetic friction.  We will assume that $\mu$
is static (otherwise the blocks would be moving relative to each
other, which means they are slipping,) and that $\mu'$ is kinetic
(otherwise they are not moving at all.)

The block of mass $m$ will slip if the force of friction between the
two blocks can not give it the same acceleration as the block of mass
$M$.  We solve for the more general case in part (ii) and obtain (i)
by setting $\mu' = 0$.  We have
\begin{align*}
  -kx + mg\mu + (m+M)g\mu' &= MA \\
  -mg\mu &= ma
\end{align*}
and we wish to know when $A \lt a$ (since the accelerations are
negative.)

Now, $m$ has maximum negative acceleration $a = -g\mu$.  If $a$ and
$A$ are just equal then
\begin{align*}
-kx + mg\mu + (m+M)g\mu' &= -Mg\mu \\
x &= \frac{-Mg\mu - mg\mu - (m+M)g\mu'}{-k} \\
&= g\frac{M\mu + m\mu + (m+M)\mu'}{k} \\
&= g\frac{(m+M)\mu + (m+M)\mu'}{k} \\
&= g\frac{(m+M)(\mu+\mu')}{k}
\end{align*}

** 3.

Presumably the work done by the seatbelt equals the kinetic energy of
the passenger; $W = F\Delta{}d = \Delta{}K =
\frac{1}{2}m(\Delta{}v)^2$.

#+BEGIN_SRC axiom
  )clear all
  F := 1/2 * m * v^2 / d
  eval(F,[m=75,v=70*10^3/3600,d=0.94])
#+END_SRC

** 4.

#+BEGIN_SRC axiom
  )read input/III.4.input
#+END_SRC

** 5.

The tension in the rope must balance gravity vertically and provide
$a$ horizontally.  Thus
#+BEGIN_SRC latex
  \begin{align*}
    T \cos \theta &= mg \\
    T \sin \theta &= ma
  \end{align*}
#+END_SRC
so that $\tan{\theta} = \frac{a}{g}$.

** 6.

If they are in series, imagine spring 1 is connected to a wall, and
consider the point between the springs and the point at the end of
spring 2.  We have
#+BEGIN_SRC latex
  \begin{align*}
    k_1 \Delta x_1 &= k_2 \Delta x_2 \\
    k_2 \Delta x_2 &= k_e \Delta x \\
    \Delta x &= \Delta x_1 + \Delta x_2 \\
    k_e &= \frac{k_2 \Delta x_2}{\Delta x_1 + \Delta x_2} \\
    &= \frac{k_2 \Delta x_2}{\frac{k_2 \Delta x_2}{k_1} + \Delta x_2} \\
    &= \frac{k_1 k_2}{k_1 + k_2}
  \end{align*}
#+END_SRC

If they are parallel, then simply $F = k_e \Delta x = k_1 \Delta x +
k_2 \Delta x$, i.e. $k = k_1 + k_2$.

** 7.

#+BEGIN_SRC latex
  \begin{align*}
    F &= m a \\
    m g \mu_s &= m \frac{v^2}{r} \\
    \mu_s &= \frac{{(2\pi r f)}^2}{g r} \\
      &= \frac{4 \pi^2 f^2 r}{g}
  \end{align*}
#+END_SRC

** 8.

#+BEGIN_SRC latex
  \begin{align*}
    T &= M g \\
    T &= m a \\
    M g &= m \frac{v^2}{R} \\
    M g &= m \frac{(\frac{2 \pi R}{T'})^2}{R} \\
    M g &= m \frac{m 4 \pi^2 R}{T'^2} \\
    T'^2 &= m \frac{4 m R \pi^2}{M g} \\
    T' &= 2 \pi \sqrt{\frac{m R}{M g}}
  \end{align*}
#+END_SRC

** 9.

#+BEGIN_SRC axiom
  )clear all
  outputGeneral(3)

  parameters := [g=9.81, m=1000, r=20]
  eqn := m*g = m*v^2/r
  eval(radicalSolve(eqn,v).1, parameters)

  parameters := concat(parameters, %)
  eqn := F = m*g + rhs(eqn)
  eval(eqn,parameters)
#+END_SRC

** 10.

#+BEGIN_SRC axiom
  )clear all
  outputGeneral(3)

  parameters := [g=9.81, m=22, theta=35*%pi/180, mu=0.68]
  eqn := F*cos(theta) = mu*(m*g + F*sin(theta))
  eqn := solve(eqn,F).1
  eval(eqn,parameters)

  eval(m*g, parameters)
#+END_SRC

** 11.

#+BEGIN_SRC axiom
  )clear all

  eqn := -M*g = -M*v^2/R
  v_min := rhs(radicalSolve(eqn, v).1)
  v_top := 2 * v_min
  eqn_top := solve(N_top + M*g = M*v_top^2/R, N_top).1
  v_bot := rhs(solve(1/2*M*v_top^2 + 2*R*M*g = 1/2*M*v_bot^2, v_bot).1)
  eqn_bot := solve(N_bot - M*g = M*v_bot^2/R, N_bot).1
#+END_SRC

** 12.

Let the \(x\)-axis be parallel to the inclined plane, and the
\(y\)-axis be perpendicular to it.  The total force on $M$ in the $y$
direction is $0$, so

\[ N = Mg\cos \alpha \,.\]

In the $x$ direction we have $F_m = -mg$, due to the tension in the
rope, and $F_g = Mg\sin \alpha$, due to gravity.  In addition, if $M$
is not moving, $F_s = -(F_m + F_k)$, up to a maximum of $\lvert F_s
\rvert = N\mu_s$.  If it is moving, we have instead $\lvert F_k \rvert
= N\mu_k$, with sign opposite of $F_m + F_k$.

(i)
$M$ will begin to slide downhill when $F_s$ has reached its maximum
and $F_m + F_g - F_s > 0$, that is

\[ -mg + Mg\sin(\alpha) - Mg\cos(\alpha)\mu_s > 0 \,.\]

Solving for $m$,

\[ m < M(sin(\alpha) - cos(\alpha)\mu_s) \,.\]

(ii)
$M$ will begin to slide uphill when $F_s$ has reached its maximum and
$F_m + F_g + F_s < 0$:

\[ -mg + Mg\sin(\alpha) + Mg\cos(\alpha)\mu_s < 0 \,.\]

In terms of $m$:

\[ m > M(sin(\alpha) + cos(\alpha)\mu_s) \,.\]

Between these values for $m$, static friction is preventing $M$ from
sliding.

If we give the masses enough of a push to overcome static friction,
then motion is still possible.  However, the motion will not continue
if kinetic friction can not be overcome.  For this to be so, we must
have $\lvert F_m + F_g \rvert \geq \lvert F_k \rvert$, or

\[ \lvert -mg + Mg\sin(\alpha) \rvert \geq Mg\cos(\alpha)\mu_k \,.\]

This happens when

\begin{align*}
  -mg + Mg\sin(\alpha) &\leq -Mg\cos(\alpha)\mu_k \\
  m - M\sin(\alpha) &\geq M\cos(\alpha)\mu_k \\
  m &\geq M(\sin(\alpha) + \cos(\alpha)\mu_k)
\end{align*}

or when

\begin{align*}
  -mg + Mg\sin(\alpha) &\geq Mg\cos(\alpha)\mu_k \\
  m - M\sin(\alpha) &\leq -M\cos(\alpha)\mu_k \\
  m &\leq M(\sin(\alpha) - \cos(\alpha)\mu_k) \,.
\end{align*}

If we increase $m$ enough, it will eventually drag $M$ uphill, because
the weight of $M$ and the static friction on it will eventually be
overcome.  However, $M$ may never be able to cause $m$ to go up, as it
may not itself move, its opposing static friction increasing
proportionally with its weight.

** 13.

The energy put into the system is the work done against the spring;

\[ \int_0^A kx\,dx =
   \left.\frac{1}{2}kx^2\right\rvert_0^A =
   \frac{1}{2}kA^2 \,.\]

(i)
At $x=0$ all energy will be kinetic; the speed will be

\begin{align*}
  \frac{1}{2}kA^2 &= \frac{1}{2}mv^2 \\
  v &= A\sqrt{\frac{k}{m}}
\end{align*}

(ii)
It will be at $x = -A$, since once again all energy is potential.

(iii)
In this case, when the mass has reached $x=0$, friction has removed
energy from the system; $\Delta E = -\mu_k N A$.  Thus the speed is

\begin{align*}
  \frac{1}{2} k A^2 -\mu_k N A &= \frac{1}{2} m v^2 \\
  k A^2 - 2 \mu_k m g A &= m v^2 \\
  v &= \sqrt{\frac{k A^2 - 2 \mu_k m g A}{m}}
\end{align*}

(iv)
Here all the energy that remains will be potential.  Friction will
have changed the energy by $\Delta E = \mu_k N (x - A)$

\begin{align*}
  \frac{1}{2} k x^2 &= \frac{1}{2} k A^2 + \mu_k N (x - A) \\
  k x^2 &= k A^2 + 2 \mu_k N (x - A) \\
  k x^2 - 2 \mu_k N x &= k A^2 - 2 \mu_k N A \\
  (k) x^2 + (-2 \mu_k N) x + (2 \mu_k N A - k A^2) &= 0 \\
  x &= \frac{2 \mu_k N \pm \sqrt{4 \mu_k^2 N^2 - 4 k (2 \mu_k N A - k A^2)}}{2 k} \\
  x &= \frac{\mu_k N \pm \sqrt{\mu_k^2 N^2 - k (2 \mu_k N A - k A^2)}}{k} \\
  x &= \frac{\mu_k N \pm \sqrt{\mu_k^2 N^2 - 2 k \mu_k N A + k^2 A^2}}{k} \\
  x &= \frac{\mu_k N \pm \sqrt{(\mu_k N - k A)^2}}{k} \\
  x &= \frac{\mu_k N \pm (\mu_k N - k A)}{k}
\end{align*}

One solution is just when the mass has not yet been released.  Thus

\[ x = \frac{2 \mu_k N - k A}{k} = \frac{2 \mu_k N}{k} - A \]
